#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : psmisc
Version  : 23.3
Release  : 21
URL      : https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.3.tar.xz
Source0  : https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: psmisc-bin = %{version}-%{release}
Requires: psmisc-license = %{version}-%{release}
Requires: psmisc-locales = %{version}-%{release}
Requires: psmisc-man = %{version}-%{release}
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : ncurses-dev
BuildRequires : tcl

%description


%package bin
Summary: bin components for the psmisc package.
Group: Binaries
Requires: psmisc-license = %{version}-%{release}

%description bin
bin components for the psmisc package.


%package license
Summary: license components for the psmisc package.
Group: Default

%description license
license components for the psmisc package.


%package locales
Summary: locales components for the psmisc package.
Group: Default

%description locales
locales components for the psmisc package.


%package man
Summary: man components for the psmisc package.
Group: Default

%description man
man components for the psmisc package.


%prep
%setup -q -n psmisc-23.3
cd %{_builddir}/psmisc-23.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578077699
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1578077699
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/psmisc
cp %{_builddir}/psmisc-23.3/COPYING %{buildroot}/usr/share/package-licenses/psmisc/74a8a6531a42e124df07ab5599aad63870fa0bd4
%make_install
%find_lang psmisc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fuser
/usr/bin/killall
/usr/bin/peekfd
/usr/bin/prtstat
/usr/bin/pslog
/usr/bin/pstree
/usr/bin/pstree.x11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/psmisc/74a8a6531a42e124df07ab5599aad63870fa0bd4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fuser.1
/usr/share/man/man1/killall.1
/usr/share/man/man1/peekfd.1
/usr/share/man/man1/prtstat.1
/usr/share/man/man1/pslog.1
/usr/share/man/man1/pstree.1

%files locales -f psmisc.lang
%defattr(-,root,root,-)

