#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: 1ab68ca
#
# Source0 file verified with key 0x022166C0FF3C84E3 (csmall@debian.org)
#
Name     : psmisc
Version  : 23.7
Release  : 29
URL      : https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz
Source0  : https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz
Source1  : https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: psmisc-bin = %{version}-%{release}
Requires: psmisc-license = %{version}-%{release}
Requires: psmisc-locales = %{version}-%{release}
Requires: psmisc-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : ncurses-dev
BuildRequires : tcl
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-dejagnu-error.patch

%description


%package bin
Summary: bin components for the psmisc package.
Group: Binaries
Requires: psmisc-license = %{version}-%{release}

%description bin
bin components for the psmisc package.


%package license
Summary: license components for the psmisc package.
Group: Default

%description license
license components for the psmisc package.


%package locales
Summary: locales components for the psmisc package.
Group: Default

%description locales
locales components for the psmisc package.


%package man
Summary: man components for the psmisc package.
Group: Default

%description man
man components for the psmisc package.


%prep
%setup -q -n psmisc-23.7
cd %{_builddir}/psmisc-23.7
%patch -P 1 -p1
pushd ..
cp -a psmisc-23.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709654361
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709654361
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/psmisc
cp %{_builddir}/psmisc-%{version}/COPYING %{buildroot}/usr/share/package-licenses/psmisc/74a8a6531a42e124df07ab5599aad63870fa0bd4 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang psmisc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/fuser
/V3/usr/bin/killall
/V3/usr/bin/peekfd
/V3/usr/bin/prtstat
/V3/usr/bin/pslog
/V3/usr/bin/pstree
/usr/bin/fuser
/usr/bin/killall
/usr/bin/peekfd
/usr/bin/prtstat
/usr/bin/pslog
/usr/bin/pstree
/usr/bin/pstree.x11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/psmisc/74a8a6531a42e124df07ab5599aad63870fa0bd4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/da/man1/prtstat.1
/usr/share/man/da/man1/pslog.1
/usr/share/man/de/man1/fuser.1
/usr/share/man/de/man1/killall.1
/usr/share/man/de/man1/peekfd.1
/usr/share/man/de/man1/prtstat.1
/usr/share/man/de/man1/pslog.1
/usr/share/man/de/man1/pstree.1
/usr/share/man/fr/man1/fuser.1
/usr/share/man/fr/man1/killall.1
/usr/share/man/fr/man1/peekfd.1
/usr/share/man/fr/man1/prtstat.1
/usr/share/man/fr/man1/pslog.1
/usr/share/man/fr/man1/pstree.1
/usr/share/man/hr/man1/fuser.1
/usr/share/man/hr/man1/killall.1
/usr/share/man/hr/man1/peekfd.1
/usr/share/man/hr/man1/prtstat.1
/usr/share/man/hr/man1/pslog.1
/usr/share/man/hr/man1/pstree.1
/usr/share/man/ko/man1/fuser.1
/usr/share/man/ko/man1/killall.1
/usr/share/man/ko/man1/peekfd.1
/usr/share/man/ko/man1/prtstat.1
/usr/share/man/ko/man1/pslog.1
/usr/share/man/ko/man1/pstree.1
/usr/share/man/man1/fuser.1
/usr/share/man/man1/killall.1
/usr/share/man/man1/peekfd.1
/usr/share/man/man1/prtstat.1
/usr/share/man/man1/pslog.1
/usr/share/man/man1/pstree.1
/usr/share/man/pt_BR/man1/fuser.1
/usr/share/man/pt_BR/man1/killall.1
/usr/share/man/pt_BR/man1/peekfd.1
/usr/share/man/pt_BR/man1/prtstat.1
/usr/share/man/pt_BR/man1/pslog.1
/usr/share/man/pt_BR/man1/pstree.1
/usr/share/man/ro/man1/fuser.1
/usr/share/man/ro/man1/killall.1
/usr/share/man/ro/man1/peekfd.1
/usr/share/man/ro/man1/prtstat.1
/usr/share/man/ro/man1/pslog.1
/usr/share/man/ro/man1/pstree.1
/usr/share/man/ru/man1/fuser.1
/usr/share/man/ru/man1/killall.1
/usr/share/man/ru/man1/peekfd.1
/usr/share/man/ru/man1/prtstat.1
/usr/share/man/ru/man1/pslog.1
/usr/share/man/ru/man1/pstree.1
/usr/share/man/sr/man1/fuser.1
/usr/share/man/sr/man1/killall.1
/usr/share/man/sr/man1/peekfd.1
/usr/share/man/sr/man1/prtstat.1
/usr/share/man/sr/man1/pslog.1
/usr/share/man/sr/man1/pstree.1
/usr/share/man/sv/man1/fuser.1
/usr/share/man/sv/man1/killall.1
/usr/share/man/sv/man1/peekfd.1
/usr/share/man/sv/man1/prtstat.1
/usr/share/man/sv/man1/pslog.1
/usr/share/man/sv/man1/pstree.1
/usr/share/man/uk/man1/fuser.1
/usr/share/man/uk/man1/killall.1
/usr/share/man/uk/man1/peekfd.1
/usr/share/man/uk/man1/prtstat.1
/usr/share/man/uk/man1/pslog.1
/usr/share/man/uk/man1/pstree.1

%files locales -f psmisc.lang
%defattr(-,root,root,-)

